dataset:
  name: "NIH Chest X-ray14"
  kaggle_slug: "nih-chest-xrays/data"
  raw_dir: "data/raw/nih-chest-xrays"
  processed_dir: "data/processed"
  image_size: 224

splits:
  seed: 42

classes:
  - "No Finding"
  - "Atelectasis"
  - "Cardiomegaly"
  - "Effusion"
  - "Infiltration"
  - "Mass"
  - "Nodule"
  - "Pneumonia"
  - "Pneumothorax"
  - "Consolidation"
  - "Edema"
  - "Emphysema"
  - "Fibrosis"
  - "Pleural_Thickening"
  - "Hernia"

multilabel: true
